### ISSUE TITLE
Typo in CMakeLists.txt

### ISSUE THREAD

**Issue by new-gen23** [prophetl33t/ShodanCPP#2]
Typo in Line 14: add_library(ShodanCPP shodanCPP/ShodanClient.h shodanCPP/ShodanClient.cpp)
Should be: add_library(ShodanCPP ShodanCPP/ShodanClient.h ShodanCPP/ShodanClient.cpp)
(capital S)

**Comment by prophetl33t** [comment]
Thanks for your feedback! Fixed.
