### ISSUE TITLE
Make Error: macro "curl_easy_setopt" passed 5 arguments, but takes just 3

### ISSUE THREAD

**Issue by new-gen23** [prophetl33t/ShodanCPP#3]
Steps I took:
cd ShodanCPP
mkdir bin
cd bin
cmake ../
make

Result:
ShodanCPP/ShodanCPP/ShodanClient.cpp:92:92: error: macro "curl_easy_setopt" passed 5 arguments, but takes just 3
   92 |  curl_easy_setopt(curl, CURLOPT_POSTFIELDS, string_format("port=%i&ips=%s"),port,ips.data());
      |                                                                                            ^
In file included from /home/newgen/c-files/ShodanCPP/ShodanCPP/ShodanClient.h:8,
                 from /home/newgen/c-files/ShodanCPP/ShodanCPP/ShodanClient.cpp:1:
/home/newgen/c-files/ShodanCPP/curl/include/curl/curl.h:2529: note: macro "curl_easy_setopt" defined here
 2529 | #define curl_easy_setopt(handle,opt,param) curl_easy_setopt(handle,opt,param)
      | 
make[2]: *** [CMakeFiles/ShodanCPP.dir/build.make:63: CMakeFiles/ShodanCPP.dir/ShodanCPP/ShodanClient.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ShodanCPP.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2

**Comment by new-gen23** [comment]
Solution: Typo in ShodanCPP/ShodanClient.cpp Line 92
curl_easy_setopt(curl, CURLOPT_POSTFIELDS, string_format("port=%i&ips=%s"),port,ips.data());
should be
curl_easy_setopt(curl, CURLOPT_POSTFIELDS, string_format("port=%i&ips=%s",port,ips.data()));
                                                                                                                                                         ^
Closing bracket for the 3rd parameter is in the wrong place.

**Comment by prophetl33t** [comment]
Good catch! Fixed it.
